lp web: Make lit-based webui render nodes
filecoin-project/lotus pull request #11519
Opened 2023-12-12 21:07 UTC by magik6k

## Related Issues
Some improvements to https://github.com/filecoin-project/lotus/pull/11516

## Proposed Changes

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

2023-12-15 00:18 UTC, snadrus requested changes

2023-12-15 00:18 UTC, snadrus commented on cmd/lotus-provider/web/api/routes.go
> +func Routes(r *mux.Router, db *harmonydb.DB) {
Please don't do this. I'm hoping to support a full set of APIs off of this server eventually.

2023-12-15 00:18 UTC, snadrus commented on cmd/lotus-provider/rpc/rpc.go
> +	web, err := web.GetSrv(ctx, dependencies.DB, dependencies.Cfg.Subsystems.GuiAddress)
lets pass in everything so we can have a rich set of API endpoints.

2024-01-09 13:47 UTC, magik6k commented
https://github.com/filecoin-project/lotus/pull/11516

2024-01-09 13:47 UTC, closed without merging