curio web: node info page
filecoin-project/lotus pull request #11745
Opened 2024-03-19 15:50 UTC by magik6k

## Related Issues

## Proposed Changes
This PR adds a "Node Info" page to the webui, adding a feature which never existed in lotus - per node storage stats view!

## Additional Info
![2024-03-19-164511_1137x924_scrot](https://github.com/filecoin-project/lotus/assets/3867941/c0ad77ed-ef84-4379-9d94-e4037ddfbe23)

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

2024-03-20 19:51 UTC, snadrus requested changes

2024-03-20 19:51 UTC, snadrus commented
Could you provide screenshots so I could see the shape/volume of the output? 
I'd like to fork this PR and build on top of it from there.

2024-03-25 08:46 UTC, magik6k commented on curiosrc/web/hapi/routes.go
There is one in the top comment

2024-03-25 15:35 UTC, snadrus approved these changes

2024-03-25 15:35 UTC, merged