feat: curioweb: Sector info page
filecoin-project/lotus pull request #11846
Opened 2024-04-06 15:13 UTC by magik6k

## Related Issues

## Proposed Changes
This PR adds an individual sector info page

## Additional Info
Screenshot:
![2024-04-06-171140_690x946_scrot](https://github.com/filecoin-project/lotus/assets/3867941/11307121-26a6-4b83-af27-3da4707ea5e0)

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

2024-04-10 16:40 UTC, magik6k commented on lib/harmony/harmonytask/task_type_handler.go
something went wrong with a rebase here..

2024-04-10 22:13 UTC, snadrus requested changes

2024-04-10 22:13 UTC, snadrus commented on curiosrc/web/hapi/simpleinfo.go
> +	err = a.db.Select(ctx, &sectorLocations, `SELECT p.can_seal, p.can_store, l.sector_filetype, l.storage_id, p.urls FROM sector_location l
please check err

2024-04-10 22:13 UTC, snadrus commented on curiosrc/web/hapi/simpleinfo.go
> +		urlList := strings.Split(loc.Urls, ",") // Assuming URLs are comma-separated
Adding SQL comments (if verified) may be useful

2024-04-10 22:13 UTC, snadrus commented on curiosrc/web/hapi/simpleinfo.go
> +			}
ids := lo.Keys(taskIDs)

2024-04-11 16:28 UTC, snadrus approved these changes

2024-04-11 16:30 UTC, merged