feat: curio: Cleanup data copies after seal ops
filecoin-project/lotus pull request #11847
Opened 2024-04-07 11:06 UTC by magik6k

## Related Issues

## Proposed Changes
This PR makes it so that after each porep pipeline step tasks will ensure that only the latest version of sector files remain in storage. This should make future retry logic much easier to implement - e.g. retrying SDR will now just be setting after_sdr/after_tree.. fields for a given sector to false.

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

2024-04-08 11:47 UTC, magik6k commented
Seems to be broken in some mysterious way, trying to debug what's going on here

2024-04-10 22:18 UTC, snadrus requested changes

2024-04-10 22:18 UTC, snadrus commented on curiosrc/ffi/sdr_funcs.go
> +func (l *storageProvider) AcquireSector(ctx context.Context, taskID *harmonytask.TaskID, sector storiface.SectorRef, existing, allocate storiface.SectorFileType, sealing storiface.PathType) (storifac
as there are 2 identical return types, can you name them?

2024-04-11 11:30 UTC, LexLuthr approved these changes

2024-04-11 16:31 UTC, snadrus approved these changes

2024-04-11 16:35 UTC, merged