feat: curio forest compat
filecoin-project/lotus pull request #12038
Opened 2024-05-23 22:26 UTC by snadrus

## Related Issues

Limited the API set in Curio to this list. 

## Proposed Changes

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:

- [ ] Commits have a clear commit message.
- [ ] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [ ] If the PR affects users (e.g., new feature, bug fix, system requirements change), update the CHANGELOG.md and add details to the UNRELEASED section.
- [ ] New features have usage guidelines and / or documentation updates in
  - [ ] [Lotus Documentation](https://lotus.filecoin.io)
  - [ ] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] Tests exist for new functionality or change in behavior
- [ ] CI is green

2024-05-23 22:26 UTC, snadrus commented
Along with the given list, Curio also needed:
- StateMinerActiveSectors
- MpoolPushMessage
- StateSectorPartition
Do we need to tell Forest about this? @LexLuthr

2024-05-24 07:44 UTC, LexLuthr requested changes
We have a usage in `chain-connectivity.mjs` as well to track chain sync. We might need to modify that to work individually with node types. We can probably handle that in the same PR where we add the Forest integration.

2024-05-24 07:44 UTC, LexLuthr commented on node/modules/storageminer.go
> +func SealProofType(maddr dtypes.MinerAddress, fnapi daemonapi.Daemon) (abi.RegisteredSealProof, error) {
Let's copy over this function to Curio deps to fix the failing tests. I think that's the cheapest solution here instead is a complicated FX dependency fix.

2024-07-18 09:03 UTC, LexLuthr commented
Closing as this has been ported.

2024-07-18 09:03 UTC, closed without merging