add support for early teminate secotrs manually
filecoin-project/lotus pull request #4433
Opened 2020-10-16 04:21 UTC by ozhtdong

2020-10-20 16:50 UTC, RobQuistNL requested changes
The current way to call it is;

```
lotus-miner proving terminate --sectors="437" --really-do-it 1
```

The current other sector edit commands are as follows:
```
lotus-miner sectors remove --really-do-it 437
```

I think you might want to move the command to the `sectors` endpoint instead of `proving`, and replace the `sectors` input. This would also be the only command that allows multiple sectors to be given in a `,` seperated way - so I'd either remove that option, or add it to all other.

Then there's also the required `--sectors` flag - whereas in other we can just use `--really-do-it`

Also, `--really-do-it` shouldn't be visible in the API output, but only visible through source code (enforcing people to know a bit of programming before they use it ;) )

I also heard that it might be better to put this entire step into the FSM as well (just like the other states).

Last but not least - Thank you! Trying to terminate 1 broken sector early now :)

2020-10-20 16:50 UTC, RobQuistNL commented on cmd/lotus-storage-miner/proving.go
> +			Usage: "specied sectors[xx,xx,xx]",
Typo? :)

2020-10-20 17:15 UTC, RobQuistNL commented
Functionally verified in 1.0.0;
https://filfox.info/en/message/bafy2bzaceacz63flwr5fhy4kafjkdiga72fpf6ujvjnnfidnypqfso5inn7tq

2020-10-20 22:20 UTC, arajasek commented
Superseded by #4507

2020-10-20 22:36 UTC, jennijuju commented
@ozhtdong Thank your for the PR first of all. Just want to let you know that we moved your implementation to lotus-shed with some ui changes(to make things more consistent with `lotus-miner sectors` cli as @RobQuistNL suggested). We moved it to `lotus-shed` so that this can be used as a utility cli for miners who wants to terminate the sectors on chain immediately. And we cant merge your pr yet b/c we will have to modify things in fsm.go for upgrading the sector status too.

2020-10-21 05:17 UTC, ozhtdong commented
@RobQuistNL  all right, I agree with and thank you for your modify, you can close this pr.

2020-10-22 15:22 UTC, closed without merging