avoid use mp.cfg directly to avoid race
filecoin-project/lotus pull request #5350
Opened 2021-01-14 03:04 UTC by GFZRZK

Since there exists a way to modify the value of mpool.cfg, it will cause a data race and create some unexpected cases.  Lock it with an RWMutex is good

2021-01-14 16:00 UTC, vyzo requested changes
Well that's fine in principle, but now we are cloning the confing _every time_ we need to access something.

I would prefer if we defined accessors that leverage the lock for the various fields instead of doing that dance, it can be quite a lot of allocations.

2021-01-14 16:01 UTC, vyzo commented
Also of note, we never modify fields of the config directly, we only read them and the setting of the config copies wholesale.
So the only potential for race is in the pointer access -- so just make a method that returns the config object with the RWLock and we'll be fine.

2021-01-14 16:03 UTC, vyzo commented
Note that this is different from GetConfig which is part of the API and returns the (cloned) config for external consumption; the new accessor should be private.

2021-01-19 18:31 UTC, vyzo approved these changes
Just a minor comment, it would be nice to write it that way.
Other than that, looks good.

2021-01-19 18:31 UTC, vyzo commented on chain/messagepool/config.go
>  	return mp.cfg.Clone()
this could be written as `getConfig().Clone()`

2021-01-30 10:31 UTC, magik6k approved these changes

2021-01-30 10:31 UTC, magik6k commented
Thanks!

2021-01-30 10:31 UTC, merged