refactor sector terminate test to use kit2
filecoin-project/lotus pull request #6507
Opened 2021-06-17 08:41 UTC by dirkmc

Depends on https://github.com/filecoin-project/lotus/pull/6506

2021-06-17 16:54 UTC, raulk requested changes

2021-06-17 16:54 UTC, raulk commented on itests/kit2/chain.go
> +func WaitTillChainHeight(ctx context.Context, t *testing.T, node *TestFullNode, blocktime time.Duration, height int) abi.ChainEpoch {
We should have this as a `TestFullNode` method. Then we can remove the `t` and `node` arguments.

2021-06-17 20:47 UTC, raulk commented on itests/kit2/chain.go
> +func WaitTillChainHeight(ctx context.Context, t *testing.T, node *TestFullNode, blocktime time.Duration, height int) abi.ChainEpoch {
Also, let's document the testkit. We are really trying to up the quality bar to make it easy for future test writers to use this framework!

2021-06-17 21:01 UTC, raulk approved these changes

2021-06-17 21:01 UTC, raulk commented on itests/kit2/node_full.go
> +func (f *TestFullNode) WaitTillChain(ctx context.Context, pred ChainPredicate) *types.TipSet {
I introduced this method, and generalised it with a little bit of functional magic. I was also able to simplify the deals itest.

2021-06-18 07:59 UTC, dirkmc commented
Nice LGTM 👍

2021-06-18 09:23 UTC, merged