Travis/fvm interopnet
filecoin-project/lotus pull request #8119
Opened 2022-02-16 23:44 UTC by travisperson

## Related Issues

## Proposed Changes

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:
- [ ] All commits have a clear commit message.
- [ ] The PR title is in the form of of `<PR type>: <area>: <change being made>`
    - example: ` fix: mempool: Introduce a cache for valid signatures`
    - `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_,_perf_, _refactor_, _revert_, _style_, _test_
    - `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_, _deps_
- [ ] This PR has tests for new functionality or change in behaviour
- [ ] If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included in https://lotus.filecoin.io or [Discussion Tutorials.](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] CI is green

2022-02-16 23:50 UTC, travisperson commented on build/params_interop.go
> +	policy.SetPreCommitChallengeDelay(abi.ChainEpoch(10))
Do we want to remove these?

2022-02-17 00:31 UTC, arajasek commented on build/params_interop.go
> +	policy.SetPreCommitChallengeDelay(abi.ChainEpoch(10))
Nah, leave em in, good for testing

2022-02-17 01:22 UTC, arajasek requested changes

2022-02-17 01:22 UTC, arajasek commented on build/params_interop.go
> +var UpgradeOhSnapHeight = abi.ChainEpoch(300)
This needs to stay disabled -- the FVM can't support v15 (the SnapDeals upgrade yet)

2022-02-18 13:44 UTC, jennijuju commented
don't forget to update the PR title according to the pr template once the PR is ready to review!

2022-03-25 21:06 UTC, arajasek approved these changes

2022-03-25 21:28 UTC, merged