test: use `T.TempDir` to create temporary test directory
filecoin-project/lotus pull request #8295
Opened 2022-03-11 06:35 UTC by Juneezee

## Related Issues
A testing enhancement.

## Proposed Changes

Replaces `ioutil.TempDir` with `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 

## Additional Info
Reference: https://pkg.go.dev/testing#T.TempDir

## Checklist

Before you mark the PR ready for review, please make sure that:
- [x] All commits have a clear commit message.
- [x] The PR title is in the form of of `<PR type>: <area>: <change being made>`
    - example: ` fix: mempool: Introduce a cache for valid signatures`
    - `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_,_perf_, _refactor_, _revert_, _style_, _test_
    - `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_, _deps_
- [ ] This PR has tests for new functionality or change in behaviour
- [ ] If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included in https://lotus.filecoin.io or [Discussion Tutorials.](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] CI is green

2022-03-14 16:12 UTC, ZenGround0 requested changes
Other than the test storage in the sector storage manager this LGTM.  It looks like you've been keeping the ioutil temp dirs around in places where the current test does not delete the dir 👍. However I am less familiar with these other tests so it's hard to be sure.

Please go through and double check there are no more places where this change will remove test directories the current tests wouldn't and then this will be good to go.

2022-03-14 16:12 UTC, ZenGround0 commented on extern/sector-storage/manager_test.go
> +	tp := t.TempDir()
This needs to be left as a ioutil temp dir to respect the `LOTUS_TEST_NO_CLEANUP` env var that was introduced for debugging

2022-03-14 23:30 UTC, ZenGround0 approved these changes

2022-03-17 11:10 UTC, magik6k approved these changes
Thanks!

2022-03-17 11:10 UTC, magik6k commented on node/repo/fsrepo_test.go
> +  //stm: @NODE_FS_REPO_LOCK_001,@NODE_FS_REPO_LOCK_002,@NODE_FS_REPO_UNLOCK_001
```suggestion
	//stm: @NODE_FS_REPO_LOCK_001,@NODE_FS_REPO_LOCK_002,@NODE_FS_REPO_UNLOCK_001
```

2022-03-17 11:10 UTC, magik6k commented on lib/backupds/backupds_test.go
> +  //stm: @OTHER_DATASTORE_RESTORE_001
```suggestion
	//stm: @OTHER_DATASTORE_RESTORE_001
```

2022-03-17 11:30 UTC, merged