ux: wallet: update delete usage
filecoin-project/lotus pull request #8442
Opened 2022-04-06 08:25 UTC by rjan90

Renaming the cmd to soft-delete to better reflect what it does -  and specify that a hard deletion is needed for permanent removal.

Should address #6926 to a degree, becuase it tells the user that extra steps are needed at least.

## Checklist

Before you mark the PR ready for review, please make sure that:
- [x] All commits have a clear commit message.
- [x] The PR title is in the form of of `<PR type>: <area>: <change being made>`
    - example: ` fix: mempool: Introduce a cache for valid signatures`
    - `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_,_perf_, _refactor_, _revert_, _style_, _test_
    - `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_, _deps_
- [ ] This PR has tests for new functionality or change in behaviour
- [x] If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included in https://lotus.filecoin.io or [Discussion Tutorials.](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] CI is green

2022-04-07 12:11 UTC, Kubuxu commented
We cannot just remove an existing command. We can rename the command but we should at least keep the old command as an alias (and maybe display a deprecation notice, when the alias is used).

2022-04-07 12:14 UTC, Kubuxu requested changes
We cannot just rename an existing command, it will break existing scripts.

We could proceed with the rename but we should add an alias to `delete` and maybe a deprecation notice. @jennijuju what do you think?

2022-04-08 23:58 UTC, Kubuxu commented
> any preference

no really, can really go either way for me

2022-04-11 18:57 UTC, arajasek commented
Updating the usage is sufficient imo.

2022-04-12 13:51 UTC, jennijuju approved these changes

2022-04-13 09:50 UTC, magik6k approved these changes

2022-04-13 09:51 UTC, merged

2022-04-19 14:52 UTC, momack2 commented
Is there any instruction we can give folks on HOW to hard delete the file? Seems like an important next step we should make accessible but very clear to avoid mistakes! Is there a “hard-delete” command we could add?