Update README.md
filecoin-project/lotus pull request #8460
Opened 2022-04-08 09:38 UTC by blademasterzhang

find the link is fault, modify https://docs.filecoin.io/get-started/lotus to https://lotus.filecoin.io

## Related Issues

## Proposed Changes

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:
- [ ] All commits have a clear commit message.
- [ ] The PR title is in the form of of `<PR type>: <area>: <change being made>`
    - example: ` fix: mempool: Introduce a cache for valid signatures`
    - `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_,_perf_, _refactor_, _revert_, _style_, _test_
    - `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_, _deps_
- [ ] This PR has tests for new functionality or change in behaviour
- [ ] If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included in https://lotus.filecoin.io or [Discussion Tutorials.](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] CI is green

2022-04-09 17:18 UTC, jennijuju requested changes

2022-04-09 17:18 UTC, jennijuju commented on README.md
> +For complete instructions on how to build, install and setup lotus, please visit [https://lotus.filecoin.io](https://lotus.filecoin.io). Basic build instructions can be found further down in this rea
```suggestion
For complete instructions on how to build, install and setup lotus, please visit [https://lotus.filecoin.io](https://lotus.filecoin.io/lotus/install/prerequisites/#supported-platforms). Basic build instructions can be found further down in this readme.
```

2022-04-09 17:19 UTC, jennijuju commented
Thank you for the PR - suggested to change to the section that can lead user directly to the installation instructions

2022-06-27 09:59 UTC, magik6k approved these changes

2022-06-27 10:00 UTC, merged