shed: util: get all msig
filecoin-project/lotus pull request #9322
Opened 2022-09-15 21:12 UTC by jennijuju

## Related Issues

## Proposed Changes

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:
- [ ] All commits have a clear commit message.
- [ ] The PR title is in the form of of `<PR type>: <area>: <change being made>`
    - example: ` fix: mempool: Introduce a cache for valid signatures`
    - `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_,_perf_, _refactor_, _revert_, _style_, _test_
    - `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_, _deps_
- [ ] This PR has tests for new functionality or change in behaviour
- [ ] If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included in https://lotus.filecoin.io or [Discussion Tutorials.](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] CI is green

2022-09-16 10:47 UTC, magik6k commented on cmd/lotus-shed/msig.go
> +		ts, err := LoadTipSet(ctx, cctx, api)
We can just call the one in `cli/` package like we do in other shed commands

2022-09-16 10:47 UTC, magik6k commented on cmd/lotus-shed/msig.go
> +	Usage: "get all multisig actor on chain with id, siigners, threshold and balance",
```suggestion
	Usage: "get all multisig actor on chain with id, signers, threshold and balance",
```

2022-09-19 21:26 UTC, arajasek requested changes
This can be _significantly_ faster (order of seconds) if we change it to work in "offline" mode -- instead of querying a daemon's API, it can work on the daemon's blockstore directly, iterating over all the actors in the state tree. See [here](https://github.com/filecoin-project/lotus/blob/e65fae28de2a44947dd24af8c7dafcade29af1a4/cmd/lotus-shed/miner-types.go#L107) for an example shed command.

2022-09-22 17:01 UTC, arajasek approved these changes
Nits but LGTM

2022-09-22 17:10 UTC, arajasek commented
And needs `make jen`

2022-09-22 19:33 UTC, merged