chore:splitstore: Update SplitStore Readme
filecoin-project/lotus pull request #9658
Opened 2022-11-16 15:20 UTC by TippyFlitsUK

Updated SplitStore Readme to show changes in https://github.com/filecoin-project/lotus/pull/9571

## Related Issues

https://github.com/filecoin-project/lotus/pull/9571

## Proposed Changes

Updates to readme file

## Additional Info

## Checklist

Before you mark the PR ready for review, please make sure that:

- [X] Commits have a clear commit message.
- [X] PR title is in the form of of `<PR type>: <area>: <change being made>`
  - example: ` fix: mempool: Introduce a cache for valid signatures`
  - `PR type`: fix, feat, build, chore, ci, docs, perf, refactor, revert, style, test
  - `area`, e.g. api, chain, state, market, mempool, multisig, networking, paych, proving, sealing, wallet, deps
- [X] New features have usage guidelines and / or documentation updates in
  - [X] [Lotus Documentation](https://lotus.filecoin.io)
  - [X] [Discussion Tutorials](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [X] Tests exist for new functionality or change in behavior
- [ ] CI is green

2022-11-21 17:15 UTC, ZenGround0 approved these changes
LGTM. Thank for this.

2022-11-21 17:15 UTC, ZenGround0 commented on blockstore/splitstore/README.md
> -- `HotStoreType` -- specifies the type of hotstore to use.
I think only the ColdStoreType config value is out of date.  All the rest are more thorough than the config comments and still relevant so if they are still relevant I'd support keeping them around.

2022-11-21 17:15 UTC, ZenGround0 commented on blockstore/splitstore/README.md
> -  - We sort cold objects heaviest first, so as to never delete the consituents of a DAG before the DAG itself (which would leave dangling references)
Nice catch removing sorting.
The "We delete in small batches ..." line is still relevant and should be kept around

2022-11-27 16:02 UTC, jennijuju requested changes

2022-11-27 16:02 UTC, jennijuju commented on blockstore/splitstore/README.md
> +  HotStoreFullGCFrequency = 20
does this mean 20 finalities?

2022-11-27 16:02 UTC, jennijuju commented on blockstore/splitstore/README.md
>  ## Configuration Options
can we explain how user should set each of these configuration base on their needs in detail? (a link to the lotus.docs.io is fine here

2022-11-28 15:31 UTC, jennijuju commented on blockstore/splitstore/README.md
> +evolves the splitstore to be a freestanding compacting blockstore that allows you to keep a small 60 GiB to 275 GiB working set in a hot blockstore and reliably archive out-of-scope objects in a cold
> The `messaqges` badger blockstore is the default storage type.

is `messaqges` a typo here?

2022-12-11 04:28 UTC, jennijuju commented on blockstore/splitstore/README.md
> +The new design (see [#9056](https://github.com/filecoin-project/lotus/pull/9056) and [#9128](https://github.com/filecoin-project/lotus/discussions/9128))
```
// CompactionThreshold is the number of epochs that need to have elapsed
	// from the previously compacted epoch to trigger a new compaction.
	//
	//        |················· CompactionThreshold ··················|
	//        |                                             |
	// =======‖≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡‖------------------------»
	//        |                    |  chain -->             ↑__ current epoch
	//        | archived epochs ___↑
	//                             ↑________ CompactionBoundary
	//
	// === :: cold (already archived)
	// ≡≡≡ :: to be archived in this compaction
	// --- :: hot
```

this graph might be useful

2022-12-12 14:48 UTC, TippyFlitsUK commented on blockstore/splitstore/README.md
> +The new design (see [#9056](https://github.com/filecoin-project/lotus/pull/9056) and [#9128](https://github.com/filecoin-project/lotus/discussions/9128))
Thanks Jen - Done

2023-11-06 13:17 UTC, closed without merging